# Generated by Django 4.2.1 on 2023-05-27 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapa',
            name='cpf',
            field=models.CharField(max_length=11, unique=True, verbose_name='CPF:'),
        ),
        migrations.AlterField(
            model_name='chapa',
            name='data_nascimento',
            field=models.DateField(max_length=50, verbose_name='Data de nacimento'),
        ),
    ]
