# Generated by Django 4.2.1 on 2023-05-27 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cel',
            field=models.CharField(default=0, max_length=11, verbose_name='Cel: 11 93758-8432'),
        ),
    ]
