# Generated by Django 4.2.1 on 2023-05-27 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_usuario_cel'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cidade',
            field=models.CharField(default='São Paulo', max_length=100, verbose_name='Cidade:'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='estado',
            field=models.CharField(default='São Paulo', max_length=100, verbose_name='Estado:'),
        ),
    ]
