# Generated by Django 4.2.1 on 2023-05-27 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_usuario_cidade_usuario_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='nome',
            field=models.CharField(default='João', max_length=255, verbose_name='Nome:'),
        ),
    ]
